services:
  - type: web
    name: leaflens-api
    env: docker
    dockerfilePath: banana_api/Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: MODEL_URL
        sync: false
      - key: MODEL_PATH
        value: /app/best_model.pth
    healthCheckPath: /
